### ISSUE TITLE
Rule idea: Check for empty files

### ISSUE THREAD

**Issue by fatbasstard** [thaim/tflint-ruleset-formatter#31]
HI, 

looking at adding this ruleset to our TFLint setup (since I live the strictness and consistency it adds) and saw somebody empty a .tf file.

My initial though: Is this rule already?

I would like a rule to check if there are empty .tf files present. They make it confusing when looking at the files (since it gives the impression resources are there).

**Comment by thaim** [comment]
Thank you for reaching out.

Checking for empty files seems like a good idea for this rule set.
Unfortunately, this rule is not yet implemented.
I'd be happy to merge it if you send a PR.

**Comment by fatbasstard** [comment]
Hi @thaim,

Cool, good to hear. I'm planning on creating rulesets myself in the future, so adding a new rule to an existing ruleset is good for me to get familiar with the setup/coding standards etc.

I'll see if I can get a PR in place
